CREATE TABLE `t_type` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `bit` bit(11) DEFAULT NULL,
  `tinyint_1` tinyint(1) DEFAULT NULL,
  `tinyint_4` tinyint(4) DEFAULT NULL,
  `smallint` smallint(11) DEFAULT NULL,
  `integer` int(10) DEFAULT NULL,
  `bigint` bigint(20) DEFAULT NULL,
  `float` float(11,0) DEFAULT NULL,
  `double` double(11,0) DEFAULT NULL,
  `decimal` decimal(11,2) DEFAULT NULL,
  `char` char(20) DEFAULT NULL,
  `varchar` varchar(20) DEFAULT NULL,
  `date` date DEFAULT NULL,
  `time` time DEFAULT NULL,
  `datetime` datetime DEFAULT NULL,
  `timestamp` timestamp NULL DEFAULT NULL,
  `binary` binary(255) DEFAULT NULL,
  `varbinary` varbinary(255) DEFAULT NULL,
  `text` text,
  `blob` blob,
  `tinytext` tinytext,
  `mediumtext` mediumtext,
  `longtext` longtext,
  `tinyblob` tinyblob,
  `mediumblob` mediumblob,
  `longblob` longblob,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
